export const SET_PAYMENT_METHOD_1 = "SET_PAYMENT_METHOD_1";
export const SET_PAYMENT_METHOD_2 = "SET_PAYMENT_METHOD_2";
export const SET_PAYMENT_DETAILS = "SET_PAYMENT_DETAILS";
export const RESET_CHECKOUT = "RESET_CHECKOUT";
export const SET_CARDS = "SET_CARDS";
export const SET_BANKS = "SET_BANKs";
export const SELECT_CARD = "SELECT_CARD";
export const SELECT_BANK = "SELECT_BANK";
export const FETCHING_START = "FETCHING_START";
export const FETCHING_SUCCESS = "FETCHING_SUCCESS";
export const FETCHING_FAIL = "FETCHING_FAIL";

export const INSERT_CB_START = "INSERT_CB_START";
export const INSERT_CB_SUCCESS = "INSERT_CB_SUCCESS";
export const INSERT_CB_FAIL = "INSERT_CB_FAIL";
